### ISSUE TITLE
Add support of `font-display` property

### ISSUE THREAD

**Issue by ArmorDarks** [betit/known-css-properties#4]
``` css
@font-face {
  font-display: swap|auto|fallback;
}
```

That property still in draft, but already supported by Chrome.

[Details](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display).
