### ISSUE TITLE
Add support of `text-size-adjust` property

### ISSUE THREAD

**Issue by ArmorDarks** [betit/known-css-properties#5]
``` css
 html { text-size-adjust: 100%; }
```

In some sense it is non-standard property, but it's commonly used by mobile browsers.

[Details](https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust).
